builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/cozy
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: cozy gen-server
    homepage: https://cozy.art

checksum:
  name_template: 'checksums.txt'

