# This configuration file provides global settings for the gen-server.
# Do not include sensitive information (tokens, keys) in a config.yaml file; place them
# inside of the .env file and access them via os.environ.get(), or use k8s secrets.

# port: 9997

# db:
#   dsn: "postgres://user:password@localhost:5432/cozy"

pipeline_defs:
  flux.1-schnell-fp8:
    source: hf:black-forest-labs/FLUX.1-schnell
    components:
      transformer:
        source: hf:cozy-creator/Flux.1-schnell-8bit
      text_encoder_2:
        source: hf:cozy-creator/Flux.1-schnell-8bit

  flux.1-dev:
    source: hf:black-forest-labs/FLUX.1-dev
  
  flux.1-dev-fp8:
    source: hf:black-forest-labs/FLUX.1-dev
    components:
      text_encoder_2:
        source: hf:cozy-creator/FLUX.1-dev-8bit
      transformer:
        source: hf:cozy-creator/FLUX.1-dev-8bit

  flux.1-dev-nf4:
    source: hf:black-forest-labs/FLUX.1-dev
    components:
      text_encoder_2:
        source: hf:hf-internal-testing/flux.1-dev-nf4-pkg
      transformer:
        source: hf:hf-internal-testing/flux.1-dev-nf4-pkg

  openflux.1:
    # community-provided diffusers pipeline; overwrites the FluxPipeline class_name from model_index.json
    # Note that if a community_pipeline is used, the class_name from model_index.json, or specified here,
    # will be ignored and replaced with the generic DiffusionPipeline class.
    custom_pipeline: pipeline_flux_with_cfg
    source: hf:ostris/OpenFLUX.1
    
  sd3.5-large-int8:
    source: hf:stabilityai/stable-diffusion-3.5-large
    components:
      transformer:
        source: hf:cozy-creator/stable-diffusion-3.5-large-8bit
      text_encoder_3:
        source: hf:cozy-creator/stable-diffusion-3.5-large-8bit

  sdxl.base:
    source: hf:stabilityai/stable-diffusion-xl-base-1.0
  
  illustrious.xl:
    class_name: StableDiffusionXLPipeline
    source: https://civitai.com/api/download/models/889818?type=Model&format=SafeTensor&size=pruned&fp=fp16
    metadata:
      display_name: Illustrious XL
      lineage: sdxl.base

  pony.v6:
    # civiitai does not provide model_index.json files, hence class_name must be specified manually
    class_name: StableDiffusionXLPipeline
    source: https://civitai.com/api/download/models/290640?type=Model&format=SafeTensor&size=pruned&fp=fp16

  cyberrealistic.pony:
    class_name: StableDiffusionXLPipeline
    source: https://civitai.com/api/download/models/953264?type=Model&format=SafeTensor&size=pruned&fp=fp16
  
  wai.ani.ponyxl:
    class_name: StableDiffusionXLPipeline
    source: https://civitai.com/api/download/models/1065370?type=Model&format=SafeTensor&size=pruned&fp=fp16

  real.dream.pony:
    class_name: StableDiffusionXLPipeline
    source: https://civitai.com/api/download/models/832353?type=Model&format=SafeTensor&size=pruned&fp=fp16

  pony.realism:
    class_name: StableDiffusionXLPipeline
    source: https://civitai.com/api/download/models/914390?type=Model&format=SafeTensor&size=full&fp=fp16

  babes_by_stable_yogi.v4.xl.fp16:
    class_name: StableDiffusionXLPipeline
    source: https://civitai.com/api/download/models/984905?type=Model&format=SafeTensor&size=full&fp=fp16
    metadata:
      display_name: Babes by Stable Yogi V4 XL
      lineage: pony.v6

  # example of all parameters:
  # playground2.5:
  #   source: hf:playgroundai/playground-v2.5-1024px-aesthetic
  #   metadata:
  #     display_name: Playground 2.5
  #     lineage: playground2.5
  #     description: whatever
  #     tags:
  #       - whatever
  #       - aesthetic
  #   class_name: null
  #   custom_pipeline:
  #   default_args:
  #     guidance_scale: 3.5
  #     num_inference_steps: 25
  #   components:
  #     scheduler:
  #       class_name: EDMDPMSolverMultistepScheduler
  #       kwargs:
  #         use_kwargs_sigmas: true
  #     text_encoder_2:
  #       class_name: transformers.CLIPTextModelWithProjection
  #       source: hf:playgroundai/playground-v2.5-1024px-aesthetic/text_encoder_2
  #     unet:
  #       lineage: playground2.5

