# This configuration file provides global settings for the gen-server.
# Do not include sensitive information (tokens, keys) in a config.yaml file; place them
# inside of the .env file and access them via os.environ.get(), or use k8s secrets.

pipeline_defs:
  flux.1-schnell-fp8:
    source: hf:black-forest-labs/FLUX.1-schnell
    components:
      transformer:
        source: hf:cozy-creator/Flux.1-schnell-8bit
      text_encoder_2:
        source: hf:cozy-creator/Flux.1-schnell-8bit

  flux.1-dev:
    source: hf:black-forest-labs/FLUX.1-dev
  
  flux.1-dev-fp8:
    source: hf:black-forest-labs/FLUX.1-dev
    components:
      text_encoder_2:
        source: hf:cozy-creator/FLUX.1-dev-8bit
      transformer:
        source: hf:cozy-creator/FLUX.1-dev-8bit

  flux.1-dev-nf4:
    source: hf:black-forest-labs/FLUX.1-dev
    components:
      text_encoder_2:
        source: hf:hf-internal-testing/flux.1-dev-nf4-pkg
      transformer:
        source: hf:hf-internal-testing/flux.1-dev-nf4-pkg

  openflux.1:
    # community-provided diffusers pipeline; overwrites the FluxPipeline class_name from model_index.json
    class_name: pipeline_flux_with_cfg
    source: hf:ostris/OpenFLUX.1
    
  sd3.5-large:
    source: hf:stabilityai/stable-diffusion-3.5-large
    components:
      transformer:
        source: hf:cozy-creator/stable-diffusion-3.5-large-8bit
      text_encoder_3:
        source: hf:cozy-creator/stable-diffusion-3.5-large-8bit

  sdxl.base:
    source: hf:stabilityai/stable-diffusion-xl-base-1.0

  pony.v6:
    # civiitai does not provide model_index.json files, hence class_name must be specified manually
    class_name: sdxl
    source: https://civitai.com/api/download/models/290640?type=Model&format=SafeTensor&size=pruned&fp=fp16

  cyberrealistic.pony:
    class_name: sdxl
    source: https://civitai.com/api/download/models/953264?type=Model&format=SafeTensor&size=pruned&fp=fp16
  
  wai.ani.ponyxl:
    class_name: sdxl
    source: https://civitai.com/api/download/models/1065370?type=Model&format=SafeTensor&size=pruned&fp=fp16

  illustrious.xl:
    class_name: sdxl 
    source: https://civitai.com/api/download/models/889818?type=Model&format=SafeTensor&size=pruned&fp=fp16

  real.dream.pony:
    class_name: sdxl
    source: https://civitai.com/api/download/models/832353?type=Model&format=SafeTensor&size=pruned&fp=fp16

  pony.realism:
    class_name: sdxl
    source: https://civitai.com/api/download/models/914390?type=Model&format=SafeTensor&size=full&fp=fp16

  playground2.5:
    source: hf:playgroundai/playground-v2.5-1024px-aesthetic

