[tool.pyright]
include = ["gen_server", "core_library"]
exclude = ["**/node_modules", "**/__pycache__"]

defineConstant = { DEBUG = true }
stubPath = "src/stubs"

reportMissingImports = true
reportMissingTypeStubs = false
