# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_defs-v1.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

# import custom_struct_v1_pb2 as custom__struct__v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12node_defs-v1.proto\x12\x08\x63omfy.v1\x1a\x16\x63ustom_struct-v1.proto"\'\n\x0eNodeDefRequest\x12\x15\n\rextension_ids\x18\x01 \x03(\t"\xcb\x04\n\x0eNodeDefinition\x12\x14\n\x0c\x64isplay_name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x31\n\x06inputs\x18\x04 \x03(\x0b\x32!.comfy.v1.NodeDefinition.InputDef\x12\x33\n\x07outputs\x18\x05 \x03(\x0b\x32".comfy.v1.NodeDefinition.OutputDef\x12\x35\n\nux_widgets\x18\x06 \x03(\x0b\x32!.comfy.v1.NodeDefinition.UXWidget\x1a\x45\n\x08UXWidget\x12\x13\n\x0bwidget_type\x18\x01 \x01(\t\x12$\n\x04spec\x18\x02 \x01(\x0b\x32\x16.comfy.v1.CustomStruct\x1a\x9b\x01\n\x08InputDef\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x11\n\tedge_type\x18\x03 \x01(\t\x12\x15\n\x08required\x18\x04 \x01(\x08H\x00\x88\x01\x01\x12\x35\n\nux_widgets\x18\x05 \x03(\x0b\x32!.comfy.v1.NodeDefinition.UXWidgetB\x0b\n\t_required\x1ax\n\tOutputDef\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x11\n\tedge_type\x18\x03 \x01(\t\x12\x35\n\nux_widgets\x18\x04 \x03(\x0b\x32!.comfy.v1.NodeDefinition.UXWidget"}\n\x08NodeDefs\x12*\n\x04\x64\x65\x66s\x18\x01 \x03(\x0b\x32\x1c.comfy.v1.NodeDefs.DefsEntry\x1a\x45\n\tDefsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.comfy.v1.NodeDefinition:\x02\x38\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "node_defs_v1_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_NODEDEFS_DEFSENTRY"]._options = None
    _globals["_NODEDEFS_DEFSENTRY"]._serialized_options = b"8\001"
    _globals["_NODEDEFREQUEST"]._serialized_start = 56
    _globals["_NODEDEFREQUEST"]._serialized_end = 95
    _globals["_NODEDEFINITION"]._serialized_start = 98
    _globals["_NODEDEFINITION"]._serialized_end = 685
    _globals["_NODEDEFINITION_UXWIDGET"]._serialized_start = 336
    _globals["_NODEDEFINITION_UXWIDGET"]._serialized_end = 405
    _globals["_NODEDEFINITION_INPUTDEF"]._serialized_start = 408
    _globals["_NODEDEFINITION_INPUTDEF"]._serialized_end = 563
    _globals["_NODEDEFINITION_OUTPUTDEF"]._serialized_start = 565
    _globals["_NODEDEFINITION_OUTPUTDEF"]._serialized_end = 685
    _globals["_NODEDEFS"]._serialized_start = 687
    _globals["_NODEDEFS"]._serialized_end = 812
    _globals["_NODEDEFS_DEFSENTRY"]._serialized_start = 743
    _globals["_NODEDEFS_DEFSENTRY"]._serialized_end = 812
# @@protoc_insertion_point(module_scope)
