# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom_struct-v1.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ustom_struct-v1.proto\x12\x08\x63omfy.v1\"\x82\x01\n\x0c\x43ustomStruct\x12\x32\n\x06\x66ields\x18\x01 \x03(\x0b\x32\".comfy.v1.CustomStruct.FieldsEntry\x1a>\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.comfy.v1.Value:\x02\x38\x01\"\xf2\x01\n\x05Value\x12)\n\nnull_value\x18\x01 \x01(\x0e\x32\x13.comfy.v1.NullValueH\x00\x12\x16\n\x0cnumber_value\x18\x02 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x03 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x12.\n\x0cstruct_value\x18\x05 \x01(\x0b\x32\x16.comfy.v1.CustomStructH\x00\x12)\n\nlist_value\x18\x06 \x01(\x0b\x32\x13.comfy.v1.ListValueH\x00\x12\x15\n\x0b\x62ytes_value\x18\x07 \x01(\x0cH\x00\x42\x06\n\x04kind\",\n\tListValue\x12\x1f\n\x06values\x18\x01 \x03(\x0b\x32\x0f.comfy.v1.Value*\x1b\n\tNullValue\x12\x0e\n\nNULL_VALUE\x10\x00\x42\x87\x01\n\x19org.comfycreator.protobufB\x11\x43ustomStructProtoP\x01Z)comfycreator.com/protobuf/custom_structpb\xf8\x01\x01\xa2\x02\x02\x43\x43\xaa\x02!ComfyCreator.Protobuf.CustomTypesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'custom_struct_v1_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031org.comfycreator.protobufB\021CustomStructProtoP\001Z)comfycreator.com/protobuf/custom_structpb\370\001\001\242\002\002CC\252\002!ComfyCreator.Protobuf.CustomTypes'
  _globals['_CUSTOMSTRUCT_FIELDSENTRY']._options = None
  _globals['_CUSTOMSTRUCT_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_NULLVALUE']._serialized_start=460
  _globals['_NULLVALUE']._serialized_end=487
  _globals['_CUSTOMSTRUCT']._serialized_start=37
  _globals['_CUSTOMSTRUCT']._serialized_end=167
  _globals['_CUSTOMSTRUCT_FIELDSENTRY']._serialized_start=105
  _globals['_CUSTOMSTRUCT_FIELDSENTRY']._serialized_end=167
  _globals['_VALUE']._serialized_start=170
  _globals['_VALUE']._serialized_end=412
  _globals['_LISTVALUE']._serialized_start=414
  _globals['_LISTVALUE']._serialized_end=458
# @@protoc_insertion_point(module_scope)
