# This configuration file provides global settings for the gen-server.
# Do not include sensitive information (tokens, keys) in a config.yaml file; place them
# inside of the .env file and access them via os.environ.get(), or use k8s secrets.

home_dir: ~/.cozy-creator
assets_path: ~/.cozy-creator/assets
models_path: ~/.cozy-creator/models
host: "0.0.0.0"
port: "8881"
filesystem_type: S3
aux_models_paths: ['/workspace/models']

s3:
  endpoint_url: "https://nyc3.digitaloceanspaces.com"
  access_key: "DO00W9N964WMQC2MV6JK"
  region_name: "nyc3"
  bucket_name: "voidtech-storage-dev"
  folder: "public"
  public_url: "https://storage.cozy.dev"

enabled_models:
  playground2.5:
    source: hf:playgroundai/playground-v2.5-1024px-aesthetic

  juggernaut-xl-v9:
    source: hf:RunDiffusion/Juggernaut-XL-v9
  
  flux.1-schnell:
    source: hf:black-forest-labs/FLUX.1-schnell
    components:
      text_encoder_2:
        source: hf:cozy-creator/flux-fp8-schnell-quantized/text_encoder_2
      transformer:
        source: hf:cozy-creator/flux-fp8-schnell-quantized/transformer
  
  pony-diffusion-xl-v6:
    source: https://civitai.com/api/download/models/290640?type=Model&format=SafeTensor&size=pruned&fp=fp16
    arch: core-extension-1.sdxl_pipe


