[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gen_server"
description = "Generative-AI server for content production"
version = "0.2.0"
authors = [
    { name = "Paul Fidika", email = "paul@fidika.com" },
    { name = "Oghenetega Biokoro", email = "teggyg123@gmail.com" }
]

dependencies = [
    "aiofiles",
    "aiohttp",
    "aiohttp_cors",
    "aiohttp_middlewares",
    "blake3",
    "boto3",
    "diffusers>=0.29",
    "einops",
    "grpcio",
    "gunicorn",
    "kornia",
    "opencv-python",
    "peft",
    "protobuf",
    "pydantic>=2.0",
    "pydantic_settings>=2.3",
    "python-dotenv",
    "safetensors>=0.4.2",
    "scikit-image",
    "sentencepiece",
    "spandrel",
    "timm",
    "transformers>=4.25",
    "tqdm",
    "typing_extensions",
    "uuid"
]

[project.optional-dependencies]
performance = [
    "accelerate",
    "triton",
    "xformers"
]

[project.scripts]
cozy = "gen_server.main:main"
cozy-creator = "gen_server.main:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["gen_server*"]
exclude = ["tests", "tests.*"]
namespaces = false

[tool.setuptools.package-data]
"gen_server" = ["py.typed"]