[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "comfy-creator"
description = "Generative-AI server for content production"
version = "0.0.2"
authors = [
    { name = "Paul Fidika", email = "paul@fidika.com" }
]
dependencies = [
    "aiohttp>=3.9.5",
    "blake3>=0.4.1",
    "boto3>=1.34.99",
    "firebase-admin>=6.5.0",
    "grpcio",
    "protobuf",
    "pulsar-client>=3.5.0",
    "pydantic>=2.7.1",
    "pydantic-settings>=2.2.1",
    "requests",
    "safetensors",
    "spandrel",
    "uuid~=1.30"
]

[project.scripts]
comfy-creator = "gen_server.main:main"
