[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "core-extension-1"
description = "Generative-AI server for content production"
version = "0.0.1"
authors = [
    { name = "Paul Fidika", email = "paul@fidika.com" }
]
dependencies = [
    "comfy_creator"
]

[project.entry-points."comfy_creator.architectures"]
sd1_text_encoder = "core_extension_1.architectures.sd1_text_encoder:SD1TextEncoderArch"
sd1_unet = "core_extension_1.architectures.sd1_unet:SD1UNetArch"
sd1_vae = "core_extension_1.architectures.sd1_vae:SD1VAEArch"
