[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "core-extension-1"
description = "Generative-AI server for content production"
version = "0.0.1"
authors = [
    { name = "Paul Fidika", email = "paul@fidika.com" }
]
dependencies = []

[project.entry-points."comfy_creator.api"]
endpoint1 = "core_extension_1.api.endpoint1:Endpoint1"
endpoint2 = "core_extension_1.api.endpoint2:Endpoint2"

[project.entry-points."comfy_creator.architectures"]
architecture1 = "core_extension_1.arch1:Architecture1"
architecture2 = "core_extension_1.arch2:Architecture2"
architecture3 = "core_extension_1.text_encoder:SD15TextEncoderArch"
architecture4 = "core_extension_1.unet:SD15UNetArch"
architecture5 = "core_extension_1.VAE:SD15VAEArch"

[project.entry-points."comfy_creator.custom_nodes"]
node1 = "core_extension_1.custom_nodes.node1:get_nodes"
node2 = "core_extension_1.custom_nodes.node1:Node1"

[project.entry-points."comfy_creator.widgets"]
widget1 = "core_extension_1.widgets:Widget1"
widget2 = "core_extension_1.widgets:Widget2"